### ISSUE TITLE
upload hidden 

### ISSUE THREAD

**Issue by svenl77** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#14]
Interesting feedback from the support. https://secure.helpscout.net/conversation/555685129/21919/

my user stores will sell nothing but simple downloaded products, so i hid the general product configuration and checked the virtual and downloaded boxes, as to cut down on user input error. this turns off the file upload box though. is there a way to hide all the product options but still leave the upload file interface in place

**Comment by marin250189** [comment]
Solved. Ready to merge`
