### ISSUE TITLE
BuddyForms Preview Page without fields has a spelling mistake.

### ISSUE THREAD

**Issue by njota08** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#40]
**Steps to reproduce:**

1. Click on BuddyForms
2. Click on Add New
3. Delete all the fields
4. Save and preview the form.

**Actual Message:**
"This form has no fields **jet**. Nothing to fill out so far. Add fields to your form to make it useful."

**Expected Message:**
"This form has no fields **yet**. Nothing to fill out so far. Add fields to your form to make it useful."

![2019-02-19_13-15-08](https://user-images.githubusercontent.com/23173178/53141972-912c9600-3568-11e9-9dfd-ca537c66f69f.jpg)

**Comment by gfirem** [comment]
This kind of issues belongs to BuddyForm repository.  @njota08 

https://github.com/BuddyForms/BuddyForms/issues

**Comment by njota08** [comment]
Fixed, tested and closed.
