### ISSUE TITLE
Names of labels, descriptions, messages for the required fields and similar should have a character limit

### ISSUE THREAD

**Issue by njota08** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#41]
On the BuddyForms, the user is allowed to write the number of characters they want on the name of labels, field's description, messages for required fields or Submit button. As far as I've tested, this behavior could be present in many other fields around the site.

This shouldn't be allowed because it may cause visual bugs as the ones you'll see on the pictures below:

![2019-02-19_23-12-51](https://user-images.githubusercontent.com/23173178/53142812-a7882100-356b-11e9-9d20-c20c096c8089.jpg)

![2019-02-19_23-28-01](https://user-images.githubusercontent.com/23173178/53142813-a7882100-356b-11e9-89ec-9f2ec0528fa0.jpg)

![2019-02-19_23-47-52](https://user-images.githubusercontent.com/23173178/53142814-a7882100-356b-11e9-8208-7e1034d210c6.jpg)

**Comment by marin250189** [comment]
@njota08 @gfirem I understand your point and thanks for identify this behavior, but following the Original Woocommerce plugin string lenght. No limit should be imposed to the strings present in the fields.

**Comment by njota08** [comment]
Got it @marin250189 , then I'll move the issue to done without further testing.
