### ISSUE TITLE
Internal Server Error (Error 500) submitting a product.

### ISSUE THREAD

**Issue by njota08** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#42]
**Steps to reproduce**

1. Click on BuddyForms
2. Click on Add New or select a product post type previously created.
3. Select a product type template in the Form Builder section
4. Customize the settings of the form.
5. Preview the form.
6. Fill the required fields and click on Submit button.

**Expected Result:** The product must be published.

**Actual Result:** Error 500 - Internal Server Error. And no message appears on the screen.

![image](https://user-images.githubusercontent.com/23173178/53143644-4c582d80-356f-11e9-8a4a-060bcaae3161.png)

**Comment by marin250189** [comment]
@njota08 Hello i could not reproduce the issue, bellow the steps i did and you tell me if i miss any step.
1-went to the BuddyForm Option
2- Clicked on Create New
3-edited the form
4-clicked preview form
5- clicked the submit button
above the image sequence of the steps
![screenshot_2](https://user-images.githubusercontent.com/11038384/53380951-88133e80-3945-11e9-93ec-cf2a77789e19.jpg)
![screenshot_3](https://user-images.githubusercontent.com/11038384/53380962-91041000-3945-11e9-822c-092c65f2844e.jpg)
![screenshot_4](https://user-images.githubusercontent.com/11038384/53380964-91041000-3945-11e9-883c-db1710aa0b16.jpg)
![screenshot_5](https://user-images.githubusercontent.com/11038384/53380965-919ca680-3945-11e9-92eb-9608cc689a2c.jpg)

**Comment by njota08** [comment]
Hello @marin250189, actually your steps are correct. 

The issue is still reproducible for me, but I think that probably is because I'm testing in a different environment(?). I mean, I'm testing in the QA site. I don't know if there are any differences but maybe that's the reason.

Here's where I'm testing: http://wordpress-68612-572859.cloudwaysapps.com/wp-admin/

**Comment by gfirem** [comment]
@marin250189 this is the error 500 in the server
```
[16-Mar-2019 03:23:05 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_Meta_Box_Product_Data::save(), 1 passed in /public_html/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php:324
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(286): WC_Meta_Box_Product_Data::save(592)
#1 /public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /wp-content/plugins/BuddyForms-WooCommerce-Form-Elements/includes/bf_woo_elem_form_elements_save.php(50): do_action('woocommerce_pro...', 592)
#4 /public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php on line 324
```

**Comment by marin250189** [comment]
this issue was solved

**Comment by njota08** [comment]
Fixed, tested and closed.
