### ISSUE TITLE
Several Tabs inside the WooCommerce Form doesn't have options

### ISSUE THREAD

**Issue by njota08** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#47]
**Steps to reproduce**

1. Click on BuddyForms
2. Click on Add New or select a product post type previously created
3. Select a WC Simple Product post type template
4. Verify that the WooCommerce section is present, if not, add it
5. Navigate between the WooCommerce tabs.

**Expected result:** All the tabs should have its options actives and the user should be able to make changes and edit.

**Actual result:** The only tabs working are "General" and "Inventory". But the tabs "Shipping", "Linked Products", "Attributes", "Variations", "Advanced" and "Front Tabs Handler" are in blank, doesn't have options and aren't editable.

![image](https://user-images.githubusercontent.com/23173178/53613042-2a802b80-3bab-11e9-87e7-df783e70e06a.png)

![image](https://user-images.githubusercontent.com/23173178/53613046-2fdd7600-3bab-11e9-9c34-4861ca2fbe9f.png)

![image](https://user-images.githubusercontent.com/23173178/53613051-3370fd00-3bab-11e9-9350-14075a685e21.png)

![image](https://user-images.githubusercontent.com/23173178/53613055-37048400-3bab-11e9-847c-52644e9593f6.png)

![image](https://user-images.githubusercontent.com/23173178/53613059-3b30a180-3bab-11e9-8c0a-fd13acecec8f.png)

![image](https://user-images.githubusercontent.com/23173178/53613062-3e2b9200-3bab-11e9-9a45-34c54e0602c9.png)

**Comment by gfirem** [comment]
@marin250189 The issue here is because the options are using `hidden` as a class and a value and now buddyform use the value as part of the class to identify each checkbox in a group.

A possible solution is to avoid `hidden` as a value for the checkboxes

**Comment by njota08** [comment]
Tested, fixed and closed.
