### ISSUE TITLE
Hide fields for Advanced section aren't working

### ISSUE THREAD

**Issue by njota08** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#61]
**Steps to reproduce**

1. Click on BuddyForms
2. Click on Add New or select a product post type previously created
3. Select a WC Simple Product post type template
4. Select the WooCommerce tab
5. Click on the "Advanced" tab
6. In the fields "Hide Purchase Notes", "Hide Menu Orders" and "Hide Enable Reviews" mark its corresponding checkbox to hide it and fill the proper fields.
7. Save and Publish your form
8. Click on Preview Form
9. Navigate to the "Advanced" tab

**Expected result:** The fields you hid should not appear on the tab. And as an enhancement, if the three options are marked to be hidden, the "Advanced" tab should not be displayed.

**Actual result:** All the fields are visible in the "Advanced" tab.

See screenshots below:

![image](https://user-images.githubusercontent.com/23173178/54331388-2f53cf00-45f0-11e9-950d-d2e5ec88f54d.png)

![image](https://user-images.githubusercontent.com/23173178/54331399-38dd3700-45f0-11e9-8317-0f5fea1b1a1c.png)

**Comment by njota08** [comment]
@gfirem @marin250189 

While testing this I noticed the following:

1. If I want to hide the "Purchase Note" or the "Menu Order" by checking its checkboxes, it will do it on the Preview Form.
2. If I mark the third checkbox to hide the "Enable Reviews", in the Preview form is being displayed.
3. If I mark the three checkboxes to hide all the options on the Advanced tab, the entire tab is hidden.

So, there's an odd behavior with the 3rd checkbox in my opinion.

I can't mark this issue as fixed if this is not behaving as expected.

**Comment by marin250189** [comment]
This issue was solved

**Comment by njota08** [comment]
The behavior is the same as the last time I tested this bug.
The 3rd option is not being hidden even if I mark the checkbox.
The only way to hide the field is by checking the 3 checkboxes and the entire tab disappear (That's ok).

**Comment by njota08** [comment]
Fixed, tested and closed.
