### ISSUE TITLE
Bookable product appear as product type and the booking plugins is not enabled

### ISSUE THREAD

**Issue by gfirem** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#63]
![image](https://user-images.githubusercontent.com/11023116/54476604-ed887b80-47dd-11e9-84ba-0f138eacafaf.png)

**Comment by marin250189** [comment]
this issue was solved

**Comment by marin250189** [comment]
@gfirem you have to merge the fix check_if_plugin_active on BF_WOO_BOOKING plugin.
