### ISSUE TITLE
If I select the Variation type the download options appear, this is not correct

### ISSUE THREAD

**Issue by gfirem** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#64]
![image](https://user-images.githubusercontent.com/11023116/54476718-50c6dd80-47df-11e9-8a1c-da4adc1fd89f.png)

@njota08 @marin250189 
This is not the correct expected behavior of the plugin.

**Comment by marin250189** [comment]
@gfirem in my local environment i don´t have this issue. i suggest to clean the cache of your browser shift+F5, the fix for the issue was included a few weeks ago.
![Screenshot_3](https://user-images.githubusercontent.com/11038384/54478346-68a25f80-47e7-11e9-924b-fb502708c5cf.jpg)
