### ISSUE TITLE
Form Element options are missing

### ISSUE THREAD

**Issue by svenl77** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#73]
**Description**
In the WooCommerce Form Element, all options are missing
 
**The steps to reproduce the issue**
Make sure Woo, BuddyForms Pro and WooElements are installed and activated.
Create a Product Form
Add the WooCommerce Form Element
Try to set up the options. Some tabs do work but the most not.

**Expected behavior**
All Form Element options should be visible.

**Screenshots**
<img width="801" alt="Bildschirmfoto 2019-05-21 um 12 38 44" src="https://user-images.githubusercontent.com/645567/58105852-1282db80-7bdf-11e9-95fb-fb3f1c3ecf49.png">

**Comment by njota08** [comment]
All the form elements options/tabs of the WooCommerce field are visible and editable in the BackEnd (While creating the form).

The "Front Tabs Handler" just show a message but there are no editable options:

![image](https://user-images.githubusercontent.com/23173178/59149741-62d3a900-89e7-11e9-8aac-37ee88b0a682.png)

In the FrontEnd there are weird behaviors that are already reported as bugs.
