### ISSUE TITLE
Create a price form element

### ISSUE THREAD

**Issue by svenl77** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#75]
Create a price form element so that people can create products without the need of using the overloaded WooCommerce form element.

Link to the Ticket: 

https://secure.helpscout.net/conversation/869822782/25423/

**Comment by gfirem** [comment]
http://price-format.github.io/Jquery-Price-Format/

**Comment by gfirem** [comment]
@svenl77 would be possible you can give us a clear picture of the desire form configuration.

**Comment by njota08** [comment]
Tested and closed.
