### ISSUE TITLE
Create Product Type Field

### ISSUE THREAD

**Issue by marin250189** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#78]
**Describe the feature**
Create the Woocommerce Product Type field.

**To Reproduce**

Create or edit a Form
Add a Woocommerce Product Type field
Save the Form
Preview the form, fill it and send it

**Expected behavior**

- Test all options on the Backend.  

  - Default Product Type: Choose In the dropdown list  the product type to set as Default  

  - Test the required validation.

- Test in the Frontend
  -Product Type Change: When change  the selected option on the  dropdownlist if the new option is any of these:(grouped product, variable product, simple subscription or variable susbcription)The price fields will hide. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11038384/59612703-913e3c00-90eb-11e9-9952-5052a73b478b.png)
Price fields hidden when option is grouped product
![image](https://user-images.githubusercontent.com/11038384/59612781-b16dfb00-90eb-11e9-911a-89b40f23ff1a.png)

**Comment by njota08** [comment]
Tested and closed.
