### ISSUE TITLE
Create Sale Price Field

### ISSUE THREAD

**Issue by marin250189** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#80]
**Describe the feature**
 New Buddyforms fields for the Woocommerce Sale  Price.
**To Reproduce**

 1. Create or edit a Form
 2. Add a Sale Price field
 3. Save the Form
 4. Preview the form, fill it and send it

**Expected behavior**
- Test the required validation.
- Test Frontend validations: On the front end the price format allowed should be the equals to the format configured on the Woocommerce settings page. When an incorrect price format is entered an instant notification should be displayed showing the cause of the validation error.
- Test Sale Price less than Regular Price validation: If the sale price entered is greater or equals to regular price a validation notification should be displayed with the error message.

**Screenshot**
![image](https://user-images.githubusercontent.com/11038384/59614113-13c7fb00-90ee-11e9-9616-24df3980bddd.png)

**Comment by njota08** [comment]
Tested and closed.
