### ISSUE TITLE
"Product Type" field - Default option isn't being kept in the FrontEnd

### ISSUE THREAD

**Issue by njota08** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#83]
*Steps to reproduce*

1. Create a "Post Simple" type form
2. Add the new "Product Type" field
*Notice that the option to edit the "Default product type" is not visible at this point*
3. Publish the form
4. Change the default Product Type
5. Save the Form
6. Click on "Preview Form"
7. In the FrontEnd verify the product type field

*Expected Result*
The default product type in the FrontEnd should be the same as the selected in the BackEnd.

*Actual Result*
The default product type in the FrontEnd always is "Simple Product"

*Screenshots*

![image](https://user-images.githubusercontent.com/23173178/59814171-58b48300-92e2-11e9-8014-c1a07c77ae9d.png)

![image](https://user-images.githubusercontent.com/23173178/59814727-52270b00-92e4-11e9-920e-c1747e53b3b4.png)

**Comment by alybarreno** [comment]
The default product type in FrontEnd is always "Simple Product". The function is done correctly.
