### ISSUE TITLE
The "Grouped WC product, WC Product All Fields y WC Simple Product" template is showing an error when you try to publish it

### ISSUE THREAD

**Issue by alybarreno** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#85]
**Describe the bug:**
By selecting the "WC Grouped product, WC Product All Fields y WC Simple Product" template and clicking on the publish button, a code error is displayed

**To Reproduce:**

1. Go to the form generator
2. Click on "Select a Template"
3. Select the template "WC Grouped Product, WC Product All Fields o WC Simple Product"
4. Click on "Publish"
5. Visualize the error

**Expected behavior:**

- You should not show code errors, the page should reload and show the fields of the form.
- The form should be published and allowed to be displayed in the frontend

**Screenshots:**

![image](https://user-images.githubusercontent.com/21145469/60107755-0e416500-972d-11e9-89bd-1734e9e8578f.png)

![image](https://user-images.githubusercontent.com/21145469/60107779-17cacd00-972d-11e9-9989-efe20dc83d74.png)

**Comment by gfirem** [comment]
@alybarreno this error was comming from BuddyForms and was fixed, please try this again.

**Comment by alybarreno** [comment]
The problem has been solved.
