### ISSUE TITLE
Error in template type "Post Form All Fields"

### ISSUE THREAD

**Issue by alybarreno** [BuddyForms/BuddyForms-WooCommerce-Form-Elements#90]
**Describe the bug:**
Error in the template of type "Post Form All Fields" when published without adding any field

**To Reproduce:**

Go to the form generator
Click on "Select a Template"
Select the template "Post Form All Fields"
Click on "Publish"
Display in the frontend
Visualize the error

**Expected behavior:**

- No error should be displayed if no field has been added
- The fields in the form must be shown

**Screenshots:**
![image](https://user-images.githubusercontent.com/21145469/60480134-05c9bc80-9c4e-11e9-8039-2325b853b9f7.png)

![image](https://user-images.githubusercontent.com/21145469/60479347-293f3800-9c4b-11e9-9607-a2c0ffceb527.png)

**Comment by gfirem** [comment]
@alybarreno I move this issue to the correct repo. I was able to reproduce the issue online.

**Comment by alybarreno** [comment]
The error has been fixed.
